#!/bin/bash
die() { echo $1; exit 1; }
git checkout master && git pull || die "failed to pull main repo"
echo 'riscoss-platform-core
riscoss-analyser
riscoss-wiki-config
riscoss-wiki-ui' | while read repo
do
    [ -e "./${repo}/.git" ] || rm -rf "./${repo}/" 2>/dev/null;
    [ -e "./${repo}/" ] || git clone "git://github.com/riscoss/${repo}.git";
    ( cd "${repo}" && git checkout master && git pull || die "failed to pull ${repo} subrepo" )
done
